BASE_MODEL = "Salesforce/codet5p-220m"

OUTPUT_DIR = "./schema_model"

MAX_SOURCE_LENGTH = 512
MAX_TARGET_LENGTH = 1024

EPOCHS = 8
LEARNING_RATE = 5e-5

BATCH_SIZE = 2
GRADIENT_ACCUMULATION = 4

WEIGHT_DECAY = 0.01
WARMUP_RATIO = 0.1
LOGGING_STEPS = 50
